language: php

php:
  - 7.4

before_install:
  - nvm install node

services:
  - mysql

before_script:
  - cp .env.example .env
  - mysql -u root -e 'CREATE DATABASE laravel;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate:install --env=testing --no-interaction
  - composer dump-autoload
  - sudo chgrp -R www-data storage bootstrap/cache
  - sudo chmod -R ug+rwx storage bootstrap/cache
  - touch database/test.sqlite
  - php artisan migrate
  - php artisan db:seed
  - php artisan storage:link
  - npm install
  - npm run production

branches:
  only:
    - main

script:
  - php artisan test
